@baseUrl = http://localhost:3000/api
@resourceName = products

# Products
# @name getAll
GET {{baseUrl}}/{{resourceName}}/
###


# @name filter
GET {{baseUrl}}/{{resourceName}}?price_gte=50&q=Dark
###


# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=1&_limit=4
###


# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=desc
###


# @name operations
GET {{baseUrl}}/{{resourceName}}?name_like=Autem&price_gte=50&price_lte=100
###


# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
  "categoryId": "729d8610-14f0-4a9f-99ef-75528bc1ce1b",
      "name": "NEW 1",
      "price": 47,
      "color": "CadetBlue",
      "description": "Id enim illo vero beatae aut quas id. Quae perspiciatis deserunt eius. Optio ullam quo natus voluptas minima repudiandae sapiente.",
      "image": "http://Wilbert.org/"
}
###


# @name update
PATCH {{baseUrl}}/{{resourceName}}/q50eGy0
Content-Type: application/json

{
  "name": "Strawberry"
}

###
# @name delete
DELETE {{baseUrl}}/{{resourceName}}/q50eGy0
Content-Type: application/json
